### ISSUE TITLE
Teams notifications not working

### ISSUE THREAD

**Issue by Krysztal** [thiagoloureiro/AlertHawk#176]
Error while trying to send teams notification via webhook.
Error: 500
WebSite: https://alerthawk.net/notifications and on premise
Version: 1.0.91 & 1.0.212

![image](https://github.com/user-attachments/assets/675d3280-56e1-4aca-8d6e-199b0e5ce339)

**Comment by thiagoloureiro** [comment]
Hi, we will investigate that :)

**Comment by thiagoloureiro** [comment]
https://github.com/thiagoloureiro/AlertHawk/pull/178

added this change, i'll deploy soon. can be tested
